/* MOVIESDREAM- MOVIES (hissa 3) */
const MOVIES3 = [
{
id:"rampage-2018",
title:"Rampage (2018)",
year:"2018",
genre:"Action, Sci-Fi",
industry:"Hollywood",
poster:"",
wiki:"Rampage_(2018_film)",
trailerId:"",
rating:"IMDb 6.1 • RT 51%",
budget:"$120 million",
boxOffice:"$428 million",
status:"Super Hit",
review:"Gorilla dost ke saath monsters se ladai."
},
{
id:"skyscraper-2018",
title:"Skyscraper (2018)",
year:"2018",
genre:"Action, Thriller",
industry:"Hollywood",
poster:"",
wiki:"Skyscraper_(2018_film)",
trailerId:"",
rating:"IMDb 5.8 • RT 48%",
budget:"$125 million",
boxOffice:"$304 million",
status:"Hit",
review:"Sabse unchi building me aag, family ko bachana hai."
},
{
id:"jungle-cruise-2021",
title:"Jungle Cruise (2021)",
year:"2021",
genre:"Adventure, Comedy",
industry:"Hollywood",
poster:"",
wiki:"Jungle_Cruise_(film)",
trailerId:"",
rating:"IMDb 6.6 • RT 62%",
budget:"$200 million",
boxOffice:"$220 million",
status:"Hit",
review:"Emily Blunt ke saath Amazon me adventure."
},
{
id:"red-notice-2021",
title:"Red Notice (2021)",
year:"2021",
genre:"Action, Comedy",
industry:"Hollywood",
poster:"",
wiki:"Red_Notice_(film)",
trailerId:"",
rating:"IMDb 6.3 • RT 37%",
budget:"$200 million",
boxOffice:"$300 million",
status:"Super Hit",
review:"Netflix ki sabse mehngi movie, Ryan Reynolds aur Gal Gadot ke saath."
},
{
id:"moana-live-action-2026",
title:"Moana (2026) Live Action",
year:"2026",
genre:"Adventure, Family",
industry:"Hollywood",
poster:"",
wiki:"Moana_(2026_film)",
trailerId:"zQjHSoVCQLs",
rating:"RT 34%",
budget:"$250 million",
boxOffice:"$266 million (abhi chal rahi)",
status:"Flop",
review:"Rock real me Maui bane, pehli baar live action me. Budget ke muqable kamai kam rahi."
},
{
id:"dr-no-1962",
title:"Dr. No (1962)",
year:"1962",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Dr._No_(film)",
trailerId:"",
rating:"IMDb 7.2 • RT 95%",
budget:"$1.1 million",
boxOffice:"$59 million",
status:"Super Hit",
review:"Pehli Bond movie, Sean Connery ki entry."
},
{
id:"from-russia-with-love-1963",
title:"From Russia with Love (1963)",
year:"1963",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"From_Russia_with_Love_(film)",
trailerId:"",
rating:"IMDb 7.4 • RT 95%",
budget:"$2 million",
boxOffice:"$78 million",
status:"Super Hit",
review:"Cold War spy thriller, best Connery movie."
},
{
id:"goldfinger-1964",
title:"Goldfinger (1964)",
year:"1964",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Goldfinger_(film)",
trailerId:"",
rating:"IMDb 7.7 • RT 99%",
budget:"$3 million",
boxOffice:"$124 million",
status:"Blockbuster",
review:"Sabse iconic Bond, Aston Martin aur Oddjob."
},
{
id:"thunderball-1965",
title:"Thunderball (1965)",
year:"1965",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Thunderball_(film)",
trailerId:"",
rating:"IMDb 7.0 • RT 87%",
budget:"$9 million",
boxOffice:"$141 million",
status:"Blockbuster",
review:"Pani ke andar action, nukes chori."
},
{
id:"you-only-live-twice-1967",
title:"You Only Live Twice (1967)",
year:"1967",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"You_Only_Live_Twice_(film)",
trailerId:"",
rating:"IMDb 6.9 • RT 73%",
budget:"$9.5 million",
boxOffice:"$111 million",
status:"Super Hit",
review:"Japan me Bond, Blofeld ki pehli face reveal."
},
{
id:"on-her-majestys-secret-service-1969",
title:"On Her Majesty's Secret Service (1969)",
year:"1969",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"On_Her_Majesty%27s_Secret_Service_(film)",
trailerId:"",
rating:"IMDb 6.8 • RT 81%",
budget:"$8 million",
boxOffice:"$82 million",
status:"Hit",
review:"George Lazenby ka ek hi Bond, emotional ending."
},
{
id:"diamonds-are-forever-1971",
title:"Diamonds Are Forever (1971)",
year:"1971",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Diamonds_Are_Forever_(film)",
trailerId:"",
rating:"IMDb 6.5 • RT 64%",
budget:"$7.2 million",
boxOffice:"$116 million",
status:"Super Hit",
review:"Connery wapas, Las Vegas me diamonds smuggling."
},
{
id:"live-and-let-die-1973",
title:"Live and Let Die (1973)",
year:"1973",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Live_and_Let_Die_(film)",
trailerId:"",
rating:"IMDb 6.7 • RT 67%",
budget:"$7 million",
boxOffice:"$161 million",
status:"Super Hit",
review:"Roger Moore ki pehli Bond entry."
},
{
id:"the-man-with-the-golden-gun-1974",
title:"The Man with the Golden Gun (1974)",
year:"1974",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"The_Man_with_the_Golden_Gun_(film)",
trailerId:"",
rating:"IMDb 6.7 • RT 40%",
budget:"$7 million",
boxOffice:"$97 million",
status:"Hit",
review:"Scaramanga ka golden gun wala villain."
},
{
id:"the-spy-who-loved-me-1977",
title:"The Spy Who Loved Me (1977)",
year:"1977",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"The_Spy_Who_Loved_Me_(film)",
trailerId:"",
rating:"IMDb 7.0 • RT 81%",
budget:"$14 million",
boxOffice:"$185 million",
status:"Blockbuster",
review:"Best Moore movie, Jaws villain ki entry."
},
{
id:"moonraker-1979",
title:"Moonraker (1979)",
year:"1979",
genre:"Action, Sci-Fi",
industry:"Hollywood",
poster:"",
wiki:"Moonraker_(film)",
trailerId:"",
rating:"IMDb 6.2 • RT 60%",
budget:"$34 million",
boxOffice:"$210 million",
status:"Blockbuster",
review:"Bond space me, Star Wars ke chakkar me bani."
},
{
id:"for-your-eyes-only-1981",
title:"For Your Eyes Only (1981)",
year:"1981",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"For_Your_Eyes_Only_(film)",
trailerId:"",
rating:"IMDb 6.7 • RT 73%",
budget:"$28 million",
boxOffice:"$195 million",
status:"Super Hit",
review:"Serious Bond, car chase zabardast."
},
{
id:"octopussy-1983",
title:"Octopussy (1983)",
year:"1983",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Octopussy",
trailerId:"",
rating:"IMDb 6.5 • RT 42%",
budget:"$27.5 million",
boxOffice:"$187 million",
status:"Super Hit",
review:"India me shoot hui Bond, circus wala scene."
},
{
id:"a-view-to-a-kill-1985",
title:"A View to a Kill (1985)",
year:"1985",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"A_View_to_a_Kill",
trailerId:"",
rating:"IMDb 6.3 • RT 37%",
budget:"$30 million",
boxOffice:"$152 million",
status:"Hit",
review:"Roger Moore ki akhri Bond movie."
},
{
id:"the-living-daylights-1987",
title:"The Living Daylights (1987)",
year:"1987",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"The_Living_Daylights",
trailerId:"",
rating:"IMDb 6.7 • RT 73%",
budget:"$40 million",
boxOffice:"$191 million",
status:"Super Hit",
review:"Timothy Dalton ki pehli entry, serious Bond."
},
{
id:"licence-to-kill-1989",
title:"Licence to Kill (1989)",
year:"1989",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Licence_to_Kill",
trailerId:"",
rating:"IMDb 6.5 • RT 79%",
budget:"$32 million",
boxOffice:"$156 million",
status:"Hit",
review:"Sabse violent Bond, revenge story."
},
{
id:"goldeneye-1995",
title:"GoldenEye (1995)",
year:"1995",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"GoldenEye",
trailerId:"",
rating:"IMDb 7.2 • RT 80%",
budget:"$60 million",
boxOffice:"$352 million",
status:"Blockbuster",
review:"Pierce Brosnan ki entry, N64 game bhi famous."
},
{
id:"tomorrow-never-dies-1997",
title:"Tomorrow Never Dies (1997)",
year:"1997",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Tomorrow_Never_Dies",
trailerId:"",
rating:"IMDb 6.5 • RT 57%",
budget:"$110 million",
boxOffice:"$333 million",
status:"Super Hit",
review:"Media mogul villain, Michelle Yeoh ke saath."
},
{
id:"the-world-is-not-enough-1999",
title:"The World Is Not Enough (1999)",
year:"1999",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"The_World_Is_Not_Enough",
trailerId:"",
rating:"IMDb 6.3 • RT 51%",
budget:"$135 million",
boxOffice:"$361 million",
status:"Super Hit",
review:"Sophie Marceau villain, oil pipeline story."
},
{
id:"die-another-day-2002",
title:"Die Another Day (2002)",
year:"2002",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Die_Another_Day",
trailerId:"",
rating:"IMDb 6.1 • RT 56%",
budget:"$142 million",
boxOffice:"$431 million",
status:"Blockbuster",
review:"Brosnan ki akhri, invisible car wali Bond."
},
{
id:"casino-royale-2006",
title:"Casino Royale (2006)",
year:"2006",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Casino_Royale_(2006_film)",
trailerId:"",
rating:"IMDb 8.0 • RT 94%",
budget:"$150 million",
boxOffice:"$616 million",
status:"Blockbuster",
review:"Daniel Craig ki pehli, sabse best modern Bond."
},
{
id:"quantum-of-solace-2008",
title:"Quantum of Solace (2008)",
year:"2008",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Quantum_of_Solace",
trailerId:"",
rating:"IMDb 6.5 • RT 64%",
budget:"$200 million",
boxOffice:"$589 million",
status:"Blockbuster",
review:"Casino Royale ka direct sequel."
},
{
id:"skyfall-2012",
title:"Skyfall (2012)",
year:"2012",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Skyfall",
trailerId:"",
rating:"IMDb 7.8 • RT 92%",
budget:"$200 million",
boxOffice:"$1.1 billion",
status:"All-Time Blockbuster",
review:"Best Bond ever, Javier Bardem villain, Adele song."
},
{
id:"spectre-2015",
title:"Spectre (2015)",
year:"2015",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"Spectre_(2015_film)",
trailerId:"",
rating:"IMDb 6.8 • RT 63%",
budget:"$245 million",
boxOffice:"$880 million",
status:"Blockbuster",
review:"Blofeld wapas, Craig aur Lea Seydoux."
},
{
id:"no-time-to-die-2021",
title:"No Time to Die (2021)",
year:"2021",
genre:"Action, Spy",
industry:"Hollywood",
poster:"",
wiki:"No_Time_to_Die",
trailerId:"",
rating:"IMDb 7.3 • RT 83%",
budget:"$250 million",
boxOffice:"$774 million",
status:"Blockbuster",
review:"Daniel Craig ki akhri Bond, emotional ending."
},
{
id:"varsity-blues-1999",
title:"Varsity Blues (1999)",
year:"1999",
genre:"Drama, Sport",
industry:"Hollywood",
poster:"",
wiki:"Varsity_Blues",
trailerId:"",
rating:"IMDb 5.9 • RT 40%",
budget:"$16 million",
boxOffice:"$54 million",
status:"Hit",
review:"Football wali pehli hit, James Van Der Beek ke saath."
},
{
id:"shes-all-that-1999",
title:"She's All That (1999)",
year:"1999",
genre:"Romance, Comedy",
industry:"Hollywood",
poster:"",
wiki:"She%27s_All_That",
trailerId:"",
rating:"IMDb 5.9 • RT 41%",
budget:"$10 million",
boxOffice:"$103 million",
status:"Super Hit",
review:"Dean Sampson bana, high school romance."
},
{
id:"the-skulls-2000",
title:"The Skulls (2000)",
year:"2000",
genre:"Thriller",
industry:"Hollywood",
poster:"",
wiki:"The_Skulls_(film)",
trailerId:"",
rating:"IMDb 5.6 • RT 9%",
budget:"$15 million",
boxOffice:"$50 million",
status:"Hit",
review:"Secret society wali thriller."
},
{
id:"joy-ride-2001",
title:"Joy Ride (2001)",
year:"2001",
genre:"Thriller, Horror",
industry:"Hollywood",
poster:"",
wiki:"Joy_Ride_(2001_film)",
trailerId:"",
rating:"IMDb 6.5 • RT 74%",
budget:"$23 million",
boxOffice:"$36 million",
status:"Average",
review:"Highway thriller, Rusty Nail truck driver se bachna hai."
},
{
id:"timeline-2003",
title:"Timeline (2003)",
year:"2003",
genre:"Sci-Fi, Adventure",
industry:"Hollywood",
poster:"",
wiki:"Timeline_(2003_film)",
trailerId:"",
rating:"IMDb 5.6 • RT 11%",
budget:"$80 million",
boxOffice:"$43 million",
status:"Flop",
review:"Time travel karke 14th century me chale gaye."
},
{
id:"into-the-blue-2005",
title:"Into the Blue (2005)",
year:"2005",
genre:"Action, Thriller",
industry:"Hollywood",
poster:"",
wiki:"Into_the_Blue_(film)",
trailerId:"",
rating:"IMDb 5.8 • RT 21%",
budget:"$50 million",
boxOffice:"$44 million",
status:"Average",
review:"Jessica Alba ke saath samundar me khazana aur drugs."
},
{
id:"eight-below-2006",
title:"Eight Below (2006)",
year:"2006",
genre:"Adventure, Family",
industry:"Hollywood",
poster:"",
wiki:"Eight_Below",
trailerId:"",
rating:"IMDb 7.3 • RT 72%",
budget:"$40 million",
boxOffice:"$120 million",
status:"Super Hit",
review:"Antarctica me 8 husky dogs ko bachana hai, emotional."
},
{
id:"running-scared-2006",
title:"Running Scared (2006)",
year:"2006",
genre:"Crime, Action",
industry:"Hollywood",
poster:"",
wiki:"Running_Scared_(2006_film)",
trailerId:"",
rating:"IMDb 7.4 • RT 41%",
budget:"$17 million",
boxOffice:"$9 million",
status:"Flop",
review:"Gangster thriller, gun dhundna hai, full dark."
},
{
id:"takers-2010",
title:"Takers (2010)",
year:"2010",
genre:"Crime, Action",
industry:"Hollywood",
poster:"",
wiki:"Takers_(film)",
trailerId:"",
rating:"IMDb 6.1 • RT 28%",
budget:"$32 million",
boxOffice:"$69 million",
status:"Hit",
review:"Bank robbery team, Chris Brown aur T.I ke saath."
},
{
id:"hours-2013",
title:"Hours (2013)",
year:"2013",
genre:"Thriller, Drama",
industry:"Hollywood",
poster:"",
wiki:"Hours_(film)",
trailerId:"",
rating:"IMDb 6.3 • RT 61%",
budget:"$4 million",
boxOffice:"$1 million",
status:"Flop",
review:"Hurricane Katrina me hospital me bache ko bachana hai, solo performance."
},
{
id:"brick-mansions-2014",
title:"Brick Mansions (2014)",
year:"2014",
genre:"Action",
industry:"Hollywood",
poster:"",
wiki:"Brick_Mansions",
trailerId:"",
rating:"IMDb 5.7 • RT 25%",
budget:"$28 million",
boxOffice:"$68 million",
status:"Hit",
review:"Paul ki akhri puri action movie, French District B13 ka remake."
},
{
id:"tenet-2020",
title:"Tenet (2020)",
year:"2020",
genre:"Sci-Fi, Action, Thriller",
industry:"Hollywood",
poster:"",
wiki:"Tenet_(film)",
trailerId:"L3pk_TBKIU4",
rating:"IMDb 7.3 • RT 69%",
budget:"$200 million",
boxOffice:"$365 million",
status:"Hit",
review:"Christopher Nolan ki time inversion wali sci-fi, ulta time."
},
{
id:"bad-boys-for-life-2020",
title:"Bad Boys for Life (2020)",
year:"2020",
genre:"Action, Comedy, Crime",
industry:"Hollywood",
poster:"",
wiki:"Bad_Boys_for_Life",
trailerId:"jKCj3A_qxp0",
rating:"IMDb 6.5 • RT 76%",
budget:"$90 million",
boxOffice:"$426 million",
status:"Blockbuster",
review:"Will Smith aur Martin Lawrence ki 17 saal baad wapsi."
},
{
id:"sonic-the-hedgehog-2020",
title:"Sonic the Hedgehog (2020)",
year:"2020",
genre:"Adventure, Comedy",
industry:"Hollywood",
poster:"",
wiki:"Sonic_the_Hedgehog_(film)",
trailerId:"szby7ZHLnkA",
rating:"IMDb 6.5 • RT 64%",
budget:"$85 million",
boxOffice:"$319 million",
status:"Super Hit",
review:"Game ka blue hedgehog, Jim Carrey villain."
},
{
id:"the-invisible-man-2020",
title:"The Invisible Man (2020)",
year:"2020",
genre:"Horror, Sci-Fi, Thriller",
industry:"Hollywood",
poster:"",
wiki:"The_Invisible_Man_(2020_film)",
trailerId:"WO_FJ4YkQ6A",
rating:"IMDb 7.1 • RT 91%",
budget:"$7 million",
boxOffice:"$144 million",
status:"Super Hit",
review:"Low budget horror lekin zabardast kamai."
},
{
id:"onward-2020",
title:"Onward (2020)",
year:"2020",
genre:"Animation, Adventure",
industry:"Hollywood",
poster:"",
wiki:"Onward_(film)",
trailerId:"gn5QmllRCn4",
rating:"IMDb 7.4 • RT 88%",
budget:"$175 million",
boxOffice:"$142 million",
status:"Flop",
review:"Pixar ki jadoo wali story, corona ki wajah se flop."
},
{
id:"bloodshot-2020",
title:"Bloodshot (2020)",
year:"2020",
genre:"Action, Sci-Fi",
industry:"Hollywood",
poster:"",
wiki:"Bloodshot_(film)",
trailerId:"vOUVVDWdXbo",
rating:"IMDb 5.7 • RT 32%",
budget:"$45 million",
boxOffice:"$37 million",
status:"Flop",
review:"Vin Diesel super soldier bana."
},
{
id:"mulan-2020",
title:"Mulan (2020)",
year:"2020",
genre:"Action, Adventure",
industry:"Hollywood",
poster:"",
wiki:"Mulan_(2020_film)",
trailerId:"KK8FHdFluOQ",
rating:"IMDb 5.7 • RT 72%",
budget:"$200 million",
boxOffice:"$70 million",
status:"Flop",
review:"Disney live action, corona me Disney+ pe gayi."
},
{
id:"soul-2020",
title:"Soul (2020)",
year:"2020",
genre:"Animation, Drama",
industry:"Hollywood",
poster:"",
wiki:"Soul_(2020_film)",
trailerId:"xOsLIi4FFr0",
rating:"IMDb 8.0 • RT 95%",
budget:"$150 million",
boxOffice:"$121 million",
status:"Hit",
review:"Pixar ka Oscar winner, rooh ki duniya."
},
{
id:"extraction-2020",
title:"Extraction (2020)",
year:"2020",
genre:"Action, Thriller",
industry:"Hollywood",
poster:"",
wiki:"Extraction_(2020_film)",
trailerId:"L6P3nI6VnlY",
rating:"IMDb 6.7 • RT 67%",
budget:"$65 million",
boxOffice:"$100M+ Netflix views",
status:"Super Hit",
review:"Chris Hemsworth ka Netflix blockbuster, Dhaka mission."
},
{
id:"enola-holmes-2020",
title:"Enola Holmes (2020)",
year:"2020",
genre:"Mystery, Adventure",
industry:"Hollywood",
poster:"",
wiki:"Enola_Holmes_(film)",
trailerId:"1d0Zf9sXlHk",
rating:"IMDb 6.6 • RT 91%",
budget:"$20 million",
boxOffice:"$80M+ Netflix views",
status:"Super Hit",
review:"Millie Bobby Brown Sherlock ki behen bani."
},
{
id:"the-old-guard-2020",
title:"The Old Guard (2020)",
year:"2020",
genre:"Action, Fantasy",
industry:"Hollywood",
poster:"",
wiki:"The_Old_Guard_(2020_film)",
trailerId:"aK-X2dHguug",
rating:"IMDb 6.6 • RT 80%",
budget:"$70 million",
boxOffice:"$100M+ Netflix views",
status:"Super Hit",
review:"Charlize Theron amar warrior bani."
},
{
id:"tanhaji-2020-bollywood",
title:"Tanhaji: The Unsung Warrior (2020)",
year:"2020",
genre:"Action, Historical, Drama",
industry:"Bollywood",
poster:"",
wiki:"Tanhaji",
trailerId:"cffAGIYTEHU",
rating:"IMDb 7.6 • RT 73%",
budget:"₹125 crore",
boxOffice:"₹367 crore",
status:"All-Time Blockbuster",
review:"Ajay Devgn ki sabse badi hit, Maratha warrior."
},
{
id:"baaghi-3-2020",
title:"Baaghi 3 (2020)",
year:"2020",
genre:"Action, Thriller",
industry:"Bollywood",
poster:"",
wiki:"Baaghi_3",
trailerId:"jxCRLe5mSCo",
rating:"IMDb 2.2 • RT 14%",
budget:"₹85 crore",
boxOffice:"₹137 crore",
status:"Hit",
review:"Tiger Shroff ka action, Syria wala mission."
},
{
id:"street-dancer-3d-2020",
title:"Street Dancer 3D (2020)",
year:"2020",
genre:"Dance, Drama",
industry:"Bollywood",
poster:"",
wiki:"Street_Dancer_3D",
trailerId:"4s8JlabahZg",
rating:"IMDb 4.7 • RT 24%",
budget:"₹70 crore",
boxOffice:"₹97 crore",
status:"Average",
review:"Varun Dhawan aur Shraddha ka dance battle."
},
{
id:"shubh-mangal-zyada-saavdhan-2020",
title:"Shubh Mangal Zyada Saavdhan (2020)",
year:"2020",
genre:"Comedy, Romance",
industry:"Bollywood",
poster:"",
wiki:"Shubh_Mangal_Zyada_Saavdhan",
trailerId:"YMy8S9DswWg",
rating:"IMDb 5.6 • RT 71%",
budget:"₹25 crore",
boxOffice:"₹86 crore",
status:"Hit",
review:"Ayushmann Khurrana gay love story, comedy."
},
{
id:"malang-2020",
title:"Malang (2020)",
year:"2020",
genre:"Action, Thriller, Romance",
industry:"Bollywood",
poster:"",
wiki:"Malang_(film)",
trailerId:"BH4rF7Bh4w4",
rating:"IMDb 6.5 • RT 50%",
budget:"₹50 crore",
boxOffice:"₹84 crore",
status:"Hit",
review:"Aditya Roy Kapur revenge story, Goa me."
},
{
id:"chhapaak-2020",
title:"Chhapaak (2020)",
year:"2020",
genre:"Drama",
industry:"Bollywood",
poster:"",
wiki:"Chhapaak",
trailerId:"h0fO1PBU0-g",
rating:"IMDb 5.2 • RT 88%",
budget:"₹35 crore",
boxOffice:"₹55 crore",
status:"Flop",
review:"Deepika Padukone acid survivor ki kahani."
},
{
id:"love-aaj-kal-2020",
title:"Love Aaj Kal (2020)",
year:"2020",
genre:"Romance, Drama",
industry:"Bollywood",
poster:"",
wiki:"Love_Aaj_Kal_(2020_film)",
trailerId:"Y8lKyuan6rs",
rating:"IMDb 5.2 • RT 18%",
budget:"₹50 crore",
boxOffice:"₹52 crore",
status:"Flop",
review:"Kartik Aaryan aur Sara Ali Khan wala remake."
},
{
id:"angrezi-medium-2020",
title:"Angrezi Medium (2020)",
year:"2020",
genre:"Comedy, Drama",
industry:"Bollywood",
poster:"",
wiki:"Angrezi_Medium",
trailerId:"sxzSL3dAxmo",
rating:"IMDb 7.0 • RT 53%",
budget:"₹36 crore",
boxOffice:"₹13 crore",
status:"Flop - Corona",
review:"Irrfan Khan ki akhri film, beti ko London bhejna."
},
{
id:"laxmii-2020",
title:"Laxmii (2020)",
year:"2020",
genre:"Horror, Comedy",
industry:"Bollywood",
poster:"",
wiki:"Laxmii",
trailerId:"x1s2G520BoU",
rating:"IMDb 3.7 • RT 12%",
budget:"₹80 crore",
boxOffice:"OTT Release",
status:"Flop",
review:"Akshay Kumar transgender bhoot, Kanchana remake."
},
{
id:"dil-bechara-2020",
title:"Dil Bechara (2020)",
year:"2020",
genre:"Romance, Drama",
industry:"Bollywood",
poster:"",
wiki:"Dil_Bechara",
trailerId:"GODAl9oVwdE",
rating:"IMDb 7.9 • RT 87%",
budget:"₹40 crore",
boxOffice:"OTT Release - Super Hit",
status:"Super Hit",
review:"Sushant Singh Rajput ki akhri movie, emotional."
},
{
id:"ala-vaikunthapurramuloo-2020",
title:"Ala Vaikunthapurramuloo (2020)",
year:"2020",
genre:"Action, Comedy, Drama",
industry:"Tollywood",
poster:"",
wiki:"Ala_Vaikunthapurramuloo",
trailerId:"S2lV0q0u2K8",
rating:"IMDb 7.3 • RT 91%",
budget:"₹75 crore",
boxOffice:"₹262 crore",
status:"Blockbuster",
review:"Allu Arjun ki sabse badi hit 2020 me, Butta Bomma song."
},
{
id:"sarileru-neekevvaru-2020",
title:"Sarileru Neekevvaru (2020)",
year:"2020",
genre:"Action, Comedy",
industry:"Tollywood",
poster:"",
wiki:"Sarileru_Neekevvaru",
trailerId:"Gk0Y1Zk0X0o",
rating:"IMDb 5.8 • RT 45%",
budget:"₹75 crore",
boxOffice:"₹260 crore",
status:"Super Hit",
review:"Mahesh Babu army major wala mass movie."
},
{
id:"bheeshma-2020-tollywood",
title:"Bheeshma (2020)",
year:"2020",
genre:"Romance, Comedy",
industry:"Tollywood",
poster:"",
wiki:"Bheeshma_(2020_film)",
trailerId:"X0lV0q0u2K9",
rating:"IMDb 6.2 • RT 60%",
budget:"₹25 crore",
boxOffice:"₹50 crore",
status:"Hit",
review:"Nithiin single ladka organic farming comedy."
},
{
id:"janu-2020-tollywood",
title:"Jaanu (2020)",
year:"2020",
genre:"Romance, Drama",
industry:"Tollywood",
poster:"",
wiki:"Jaanu_(2020_film)",
trailerId:"",
rating:"IMDb 7.0 • RT 70%",
budget:"₹20 crore",
boxOffice:"₹28 crore",
status:"Average",
review:"96 Tamil ka Telugu remake, Samantha."
},
{
id:"v-2020-tollywood",
title:"V (2020)",
year:"2020",
genre:"Action, Thriller",
industry:"Tollywood",
poster:"",
wiki:"V_(2020_film)",
trailerId:"",
rating:"IMDb 6.5 • RT 40%",
budget:"₹45 crore",
boxOffice:"OTT Release Amazon",
status:"Average",
review:"Nani negative role me, cop vs killer."
},
{
id:"nishabdham-2020",
title:"Nishabdham (2020)",
year:"2020",
genre:"Thriller, Horror",
industry:"Tollywood",
poster:"",
wiki:"Nishabdham",
trailerId:"",
rating:"IMDb 4.4 • RT 20%",
budget:"₹25 crore",
boxOffice:"OTT Release Amazon",
status:"Flop",
review:"Anushka Shetty mute artist thriller USA me."
},
{
id:"other-mommy-2026",
title:"Other Mommy (2026)",
year:"2026",
genre:"Horror",
industry:"Hollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"9 October 2026 ko theatres mein aa rahi hai."
},
{
id:"animals-2026",
title:"Animals (2026)",
year:"2026",
genre:"Thriller",
industry:"Hollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Ben Affleck ki directed film, Kerry Washington aur Gillian Anderson ke saath. 9 October 2026 ko theatres mein aur Netflix par."
},
{
id:"street-fighter-2026",
title:"Street Fighter (2026)",
year:"2026",
genre:"Action",
industry:"Hollywood",
poster:"",
wiki:"Street_Fighter_(2026_film)",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Mashhoor video game ki live action movie. Noah Centineo, Jason Momoa aur Roman Reigns cast mein hain. 16 October 2026 release."
},
{
id:"whalefall-2026",
title:"Whalefall (2026)",
year:"2026",
genre:"Thriller",
industry:"Hollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Samundar ke andar survival thriller. 16 October 2026 ko release hogi."
},
{
id:"clayface-2026",
title:"Clayface (2026)",
year:"2026",
genre:"Horror, Sci-Fi",
industry:"Hollywood",
poster:"",
wiki:"Clayface_(film)",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"DC ka Clayface, Batman universe ka villain. Tom Rhys Harries lead role mein hain. 23 October 2026 release."
},
{
id:"wildwood-2026",
title:"Wildwood (2026)",
year:"2026",
genre:"Animation, Fantasy",
industry:"Hollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Fantasy animation adventure. 23 October 2026 ko release hogi."
},
{
id:"dune-part-three-2026",
title:"Dune: Part Three (2026)",
year:"2026",
genre:"Sci-Fi",
industry:"Hollywood",
poster:"",
wiki:"Dune:_Part_Three",
trailerId:"",
rating:"Most Awaited",
budget:"$250 million",
boxOffice:"Releasing on 18 Dec 2026",
status:"Most Awaited",
review:"18 December 2026 ko release hogi. Denis Villeneuve ki trilogy ka end, Timothee Chalamet aur Zendaya wapas. Dune Messiah book pe based hai."
},
{
id:"udta-teer-2026",
title:"Udta Teer (2026)",
year:"2026",
genre:"Action, Drama",
industry:"Bollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Ayushmann Khurrana aur Sara Ali Khan ki film. 9 October 2026 ko release hogi."
},
{
id:"prahaar-2026",
title:"Prahaar (2026)",
year:"2026",
genre:"Action",
industry:"Bollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Rajkummar Rao ki action film. 16 October 2026 ko release hogi."
},
{
id:"nayyi-navelli-2026",
title:"Nayyi Navelli (2026)",
year:"2026",
genre:"Drama",
industry:"Bollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Yami Gautam ki film. 16 October 2026 ko release hogi."
},
{
id:"king-2026",
title:"King (2026)",
year:"2026",
genre:"Action",
industry:"Bollywood",
poster:"",
wiki:"King_(2026_film)",
trailerId:"",
rating:"Most Awaited",
budget:"$120 million",
boxOffice:"Releasing on 24 Dec 2026",
status:"Most Awaited",
review:"24 December 2026 ko release hogi. Shah Rukh Khan ki film, Siddharth Anand ka direction, Suhana Khan aur Deepika Padukone ke saath."
},
{
id:"ak-47-2026",
title:"Aadarsha Kutumbam House No 47 - AK 47 (2026)",
year:"2026",
genre:"Family, Drama",
industry:"Tollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Venkatesh ki family entertainer. 9 October 2026 ko release hogi."
},
{
id:"alcohol-2026",
title:"Alcohol (2026)",
year:"2026",
genre:"Drama",
industry:"Tollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Allari Naresh aur Ruhani Sharma ki film. 9 October 2026 ko release hogi."
},
{
id:"comrade-kalyan-2026",
title:"Comrade Kalyan (2026)",
year:"2026",
genre:"Drama",
industry:"Tollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Sree Vishnu aur Mahima Nambiar ki film. 9 October 2026 ko release hogi."
},
{
id:"saradaa-2026",
title:"Saradaa (2026)",
year:"2026",
genre:"Drama",
industry:"Tollywood",
poster:"",
wiki:"",
trailerId:"",
rating:"Abhi release nahi hui",
budget:"TBA",
boxOffice:"Release ke baad update hoga",
status:"Coming Soon",
review:"Manchu Vishnu ki film. 9 October 2026 ko release hogi."
}
];
